# Generated by Django 6.0 on 2026-01-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimate_time',
            field=models.IntegerField(default=24, help_text='Duration in Hours'),
        ),
    ]
