# Generated by Django 6.0 on 2026-01-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_mod',
            new_name='payment_method',
        ),
    ]
